"""Añadir campo fecha_limite_presentacion

Revision ID: 5bef378478fe
Revises: 
Create Date: 2025-04-16 14:54:24.602078

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = '5bef378478fe'
down_revision = None
branch_labels = None
depends_on = None


import datetime

def upgrade():
    with op.batch_alter_table('solicitud_subvencion', schema=None) as batch_op:
        default_date = datetime.date.today().strftime("%Y-%m-%d")
        batch_op.add_column(
            sa.Column('fecha_limite_presentacion', sa.Date(), nullable=False, server_default=sa.text(f"'{default_date}'"))
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('ADMIN', 'GESTOR', 'CONSULTA', name='user_role'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'GESTOR', 'CONSULTA', name='user_role'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    with op.batch_alter_table('solicitud_subvencion', schema=None) as batch_op:
        batch_op.drop_column('fecha_limite_presentacion')

    # ### end Alembic commands ###
