"""Inicialización completa con campo bloqueada

Revision ID: ccb4c9a8e4a7
Revises: 
Create Date: 2025-04-23 14:30:05.837205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb4c9a8e4a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'GESTOR', 'CONSULTA', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('solicitud_subvencion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expediente_opensea', sa.String(length=120), nullable=False),
    sa.Column('expediente_subvencion', sa.String(length=120), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=False),
    sa.Column('tipo_fondo', sa.Enum('Europeo', 'Nacional', 'Autonómico', 'Provincial', 'Otros', name='tipo_fondo_enum'), nullable=False),
    sa.Column('importe_total', sa.Float(), nullable=True),
    sa.Column('importe_subvencionado', sa.Float(), nullable=True),
    sa.Column('fondos_propios', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('EN_TRAMITE', 'NO_SOLICITADA', 'SOLICITADA', 'ALEGACIONES', 'CONCEDIDA_PROVISIONAL', 'CONCEDIDA', 'DENEGADA', name='estado_solicitud'), nullable=False),
    sa.Column('motivo_no_solicitada', sa.String(length=255), nullable=True),
    sa.Column('motivo_denegada', sa.String(length=255), nullable=True),
    sa.Column('fecha_limite_presentacion', sa.Date(), nullable=False),
    sa.Column('fecha_presentacion_solicitud', sa.Date(), nullable=True),
    sa.Column('fecha_resolucion_provisional', sa.Date(), nullable=True),
    sa.Column('fecha_resolucion_definitiva', sa.Date(), nullable=True),
    sa.Column('gestor_responsable', sa.String(length=100), nullable=True),
    sa.Column('email_gestor', sa.String(length=120), nullable=True),
    sa.Column('doc_inicio_expediente', sa.Boolean(), nullable=True),
    sa.Column('doc_informe_tecnico', sa.Boolean(), nullable=True),
    sa.Column('doc_propuesta_jgl', sa.Boolean(), nullable=True),
    sa.Column('doc_ficha_captacion', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bloqueada', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidad.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_subvencion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observacion_solicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitud_subvencion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observacion_solicitud')
    op.drop_table('historial_solicitud')
    op.drop_table('solicitud_subvencion')
    op.drop_table('users')
    op.drop_table('entidad')
    # ### end Alembic commands ###
